name: run-python-script
run-name: ${{ github.actor }} is running a Python script
on:
  pull_request:
    branches:
      - main
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run script.
        run: python my_python_script.py
