name: unit-tests
run-name: ${{ github.actor }} is running unit tests
on:
  pull_request:
    branches:
      - main
    paths:
      - utilities
      - .github/workflows/unit-tests.yml
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install requirements.
        run: pip install -r requirements.txt
      - name: Run tests.
        run: pytest -vv ./utilities/tests/test_calculator.py
